import { initializeApp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import { getAuth,signInWithEmailAndPassword,signOut,onAuthStateChanged,setPersistence,browserLocalPersistence } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { getFirestore,collection,getDocs,doc,setDoc,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { firebaseConfig,isConfigured } from "../js/config.js";
const $=s=>document.querySelector(s);let auth,db,user,monthCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1),bookings=[],inventory=[];const STAFF_EMAIL="51bbsadmin@gmai.com";
function msg(sel,text,type=""){const el=$(sel);if(!el)return;el.textContent=text;el.className=`message ${type}`.trim()}
function ymd(d){return d.toLocaleDateString("en-CA")} function ym(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
async function token(){return await user.getIdToken()}
async function fetchCalendar(){const r=await fetch(`/api/housekeeping-calendar?month=${encodeURIComponent(ym(monthCursor))}`,{headers:{Authorization:`Bearer ${await token()}`}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||"日曆讀取失敗");bookings=(await r.json()).bookings||[];renderCalendar()}
function nights(b){const out=[];let d=new Date(`${b.startDate}T00:00:00`),e=new Date(`${b.endDate}T00:00:00`);while(d<e){out.push(ymd(d));d.setDate(d.getDate()+1)}return out}
function bookingsForDay(day){return bookings.filter(b=>day>=b.startDate&&day<b.endDate)}
function renderCalendar(){const title=$("#monthTitle"),grid=$("#calendarGrid");title.textContent=`${monthCursor.getFullYear()} 年 ${monthCursor.getMonth()+1} 月`;grid.replaceChildren();const y=monthCursor.getFullYear(),m=monthCursor.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate();for(let i=0;i<first.getDay();i++){const e=document.createElement("div");e.className="day empty";grid.append(e)}const today=ymd(new Date());for(let n=1;n<=days;n++){const d=new Date(y,m,n),day=ymd(d),rows=bookingsForDay(day);const btn=document.createElement("button");btn.type="button";btn.className=`day${day===today?" today":""}${rows.length?" has-stay":""}`;btn.innerHTML=`<span class="num">${n}</span>${rows.length?`<span class="count">${rows.length} 組住宿<br>${rows.slice(0,2).map(x=>x.guestName).join("、")}</span>`:""}`;btn.addEventListener("click",()=>{document.querySelectorAll(".day.selected").forEach(x=>x.classList.remove("selected"));btn.classList.add("selected");renderDay(day)});grid.append(btn)}const defaultDay=today.startsWith(ym(monthCursor))?today:ymd(new Date(y,m,1));renderDay(defaultDay)}
function renderDay(day){$("#selectedTitle").textContent=`${day.replaceAll("-","/")} 住宿名單`;const box=$("#dayBookings"),rows=bookingsForDay(day);box.replaceChildren();if(!rows.length){box.innerHTML='<div class="booking"><div class="meta">這一天目前沒有住宿。</div></div>';return}rows.forEach(b=>{const el=document.createElement("article");el.className="booking";el.innerHTML=`<strong>${escapeHtml(b.guestName)}</strong><div class="meta">${b.startDate} 入住 → ${b.endDate} 退房</div><div class="meta">${b.people} 人</div><span class="badge ${b.status==='pending'?'pending':''}">${b.status==='confirmed'?'已確認':'待確認'}</span>`;box.append(el)})}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function loadInventory(){const snap=await getDocs(collection(db,"inventoryItems"));inventory=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(a.name||"").localeCompare(String(b.name||""),"zh-Hant"));renderInventory()}
function renderInventory(){const list=$("#inventoryList"),sel=$("#stockItem");list.replaceChildren();sel.innerHTML='<option value="">請選備品</option>';if(!inventory.length)list.innerHTML='<div class="inventory"><div>目前還沒有備品。</div></div>';for(const i of inventory){const qty=Number(i.quantity)||0,min=Number(i.minQuantity)||0;const el=document.createElement("article");el.className=`inventory${qty<=min&&min>0?" low":""}`;el.innerHTML=`<strong>${escapeHtml(i.name)}</strong><span class="qty">${qty} ${escapeHtml(i.unit||"")}</span><div class="meta">安全庫存 ${min} ${escapeHtml(i.unit||"")}${qty<=min&&min>0?" · ⚠️ 低庫存":""}</div>`;list.append(el);const o=document.createElement("option");o.value=i.id;o.textContent=`${i.name}（${qty} ${i.unit||""}）`;sel.append(o)}}
async function saveMovement(e){e.preventDefault();const id=$("#stockItem").value,qty=Number($("#stockQty").value),action=$("#stockAction").value;if(!id||!(qty>0))return msg("#stockMessage","請選備品並輸入數量。","error");const item=inventory.find(x=>x.id===id);if(!item)return;const current=Number(item.quantity)||0,next=action==="in"?current+qty:current-qty;if(next<0)return msg("#stockMessage","庫存不足，請確認領用數量。","error");msg("#stockMessage","正在儲存…");await setDoc(doc(db,"inventoryItems",id),{...item,quantity:next,updatedAt:serverTimestamp(),updatedBy:user.uid},{merge:true});await setDoc(doc(collection(db,"inventoryTransactions")),{itemId:id,itemName:item.name,action,quantity:qty,beforeQuantity:current,afterQuantity:next,date:ymd(new Date()),note:$("#stockNote").value.trim(),createdBy:user.uid,createdAt:serverTimestamp()});e.target.reset();msg("#stockMessage","庫存已更新。","success");await loadInventory()}
async function saveItem(e){e.preventDefault();const name=$("#itemName").value.trim(),unit=$("#itemUnit").value.trim(),quantity=Number($("#itemQty").value)||0,minQuantity=Number($("#itemMin").value)||0;if(!name||!unit)return msg("#itemMessage","請填寫備品名稱與單位。","error");await setDoc(doc(collection(db,"inventoryItems")),{name,unit,quantity,minQuantity,unitCost:0,createdBy:user.uid,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});e.target.reset();msg("#itemMessage","備品已新增。","success");await loadInventory()}
function bind(){
$("#loginForm").addEventListener("submit",async e=>{e.preventDefault();const email=$("#email").value.trim().toLowerCase();if(email!==STAFF_EMAIL)return msg("#loginMessage","此帳號沒有房務權限。","error");try{await signInWithEmailAndPassword(auth,email,$("#password").value)}catch{msg("#loginMessage","登入失敗，請確認帳號與密碼。","error")}});
$("#logoutButton").addEventListener("click",()=>signOut(auth));$("#prevMonth").addEventListener("click",async()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()-1,1);await fetchCalendar()});$("#nextMonth").addEventListener("click",async()=>{monthCursor=new Date(monthCursor.getFullYear(),monthCursor.getMonth()+1,1);await fetchCalendar()});$("#refreshInventory").addEventListener("click",loadInventory);$("#movementForm").addEventListener("submit",saveMovement);$("#itemForm").addEventListener("submit",saveItem);document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>switchWorkspace(b.dataset.tab)));document.querySelectorAll(".bottom-tab").forEach(b=>b.addEventListener("click",()=>switchWorkspace(b.dataset.go)))}
function switchWorkspace(name){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===name));document.querySelectorAll(".bottom-tab").forEach(x=>x.classList.toggle("active",x.dataset.go===name));$("#calendarPanel").classList.toggle("hidden",name!=="calendar");$("#inventoryPanel").classList.toggle("hidden",name!=="inventory");if(name==="inventory")loadInventory()}
async function init(){if(!isConfigured())return msg("#loginMessage","Firebase 尚未設定完成。","error");const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);await setPersistence(auth,browserLocalPersistence);bind();onAuthStateChanged(auth,async u=>{if(!u){user=null;$("#loginView").classList.remove("hidden");$("#appView").classList.add("hidden");return}if(String(u.email||"").toLowerCase()!==STAFF_EMAIL){await signOut(auth);return}user=u;$("#accountEmail").textContent=u.email;$("#loginView").classList.add("hidden");$("#appView").classList.remove("hidden");try{await Promise.all([fetchCalendar(),loadInventory()])}catch(e){console.error(e);alert("房務資料讀取失敗，請重新整理或確認權限設定。")}})}init();
