const TOKEN_URL="https://oauth2.googleapis.com/token";
function cfg(){return{clientId:String(process.env.GMAIL_CLIENT_ID||"").trim(),clientSecret:String(process.env.GMAIL_CLIENT_SECRET||"").trim(),refreshToken:String(process.env.GMAIL_REFRESH_TOKEN||"").trim(),sender:String(process.env.GMAIL_SENDER_EMAIL||"").trim(),senderName:String(process.env.GMAIL_SENDER_NAME||"俐姐的家").trim()};}
export function gmailReady(){const c=cfg();return Boolean(c.clientId&&c.clientSecret&&c.refreshToken&&c.sender);}
export function adminNotificationEmail(){const c=cfg();return String(process.env.ADMIN_NOTIFICATION_EMAIL||c.sender||"").trim();}
async function access(){const c=cfg();if(!gmailReady())throw new Error("GMAIL_NOT_CONFIGURED");const r=await fetch(TOKEN_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:c.refreshToken,grant_type:"refresh_token"})});if(!r.ok)throw new Error(`GMAIL_TOKEN_FAILED ${r.status} ${await r.text()}`);return(await r.json()).access_token;}
function clean(v){return String(v||"").replace(/[\r\n]+/g," ").trim();}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
export async function sendMail({to,subject,text,html}){if(!to)return{skipped:true};const c=cfg(),tok=await access();let body; if(html){const boundary=`lijie_${Date.now().toString(36)}`;body=[`From: ${clean(c.senderName)} <${clean(c.sender)}>` ,`To: ${clean(to)}`,`Subject: =?UTF-8?B?${Buffer.from(String(subject),"utf8").toString("base64")}?=`,`MIME-Version: 1.0`,`Content-Type: multipart/alternative; boundary="${boundary}"`,"",`--${boundary}`,`Content-Type: text/plain; charset=UTF-8`,`Content-Transfer-Encoding: 8bit`,"",String(text||""),`--${boundary}`,`Content-Type: text/html; charset=UTF-8`,`Content-Transfer-Encoding: 8bit`,"",String(html||""),`--${boundary}--`,""].join("\r\n");}else{body=[`From: ${clean(c.senderName)} <${clean(c.sender)}>` ,`To: ${clean(to)}`,`Subject: =?UTF-8?B?${Buffer.from(String(subject),"utf8").toString("base64")}?=`,`MIME-Version: 1.0`,`Content-Type: text/plain; charset=UTF-8`,`Content-Transfer-Encoding: 8bit`,"",String(text||"")].join("\r\n");}const r=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send",{method:"POST",headers:{Authorization:`Bearer ${tok}`,"Content-Type":"application/json"},body:JSON.stringify({raw:Buffer.from(body,"utf8").toString("base64url")})});if(!r.ok)throw new Error(`GMAIL_SEND_FAILED ${r.status} ${await r.text()}`);return{ok:true};}
export function receivedEmailText(b){const test=Boolean(b.isTest);return[`${b.guestName||b.name||"您好"} 您好：`,"",test?"【測試模式】這是一筆測試預約，不會列入正式營運統計。":"我們已收到您在「俐姐的家」送出的預約需求。","",`預約編號：${b.id||"—"}`,`入住日期：${b.startDate||b.checkIn}`,`退房日期：${b.endDate||b.checkOut}`,`入住人數：${b.people?`${b.people} 人`:"未填"}`,"",`固定訂金：NT$ 3,000`,"目前狀態：預約申請已收到，等待訂金入帳。","此封信代表已收到需求，尚不代表預約正式成立。須先完成 NT$3,000 訂金，並由俐姐於官網後台確認後才正式成立。","","付款資訊：高雄市鳥松區農會｜農分會代號 619-1089｜戶名 吳俐潔 小姐｜匯款帳號 01089210623310",...(test?["","測試提醒：測試訂單確認時不會鎖定正式官網日期，可由後台一鍵清除測試資料。"]:[]),"","俐姐的家"].join("\n");}
export function confirmedEmailText(b){const test=Boolean(b.isTest);return[`${b.guestName||"您好"} 您好：`,"",test?"【測試模式】您的測試預約流程已完成。":"您的「俐姐的家」預約已確認。","",`預約編號：${b.id||"—"}`,`入住日期：${b.startDate}`,`退房日期：${b.endDate}`,`入住人數：${b.people?`${b.people} 人`:"未填"}`,...(Number(b.quotedTotal)>0?[`住宿總額：NT$ ${Number(b.quotedTotal).toLocaleString("zh-TW")}`]:[]),"","訂金 NT$3,000 已確認入帳。",test?"此為測試訂單，不會鎖定正式預約日期，也不列入正式營運統計。":"本次預約已正式成立。",...(test?[]:["尾款與住宿細節，請以官方 LINE 的通知與雙方確認內容為準。"]),"","俐姐的家"].join("\n");}
function siteBase(){return String(process.env.PUBLIC_SITE_URL||process.env.SITE_URL||"https://www.5-1bbs.com").trim().replace(/\/$/,"");}
export function adminOperationsUrl(b){const q=new URLSearchParams({tab:"operations"});if(b?.startDate)q.set("date",String(b.startDate));if(b?.id)q.set("booking",String(b.id));return `${siteBase()}/admin/?${q.toString()}`;}
export function newBookingAdminMail(b){const total=Number(b.totalAmount??b.quotedTotal??0)||0,dep=Number(b.depositRequired||3000)||3000,url=adminOperationsUrl(b),test=Boolean(b.isTest);const subject=`俐姐的家｜${test?"【測試】":""}新訂單 ${b.startDate||""} ${b.guestName||"未填"}`;const text=[test?"【測試訂單】":"【新訂單通知】",`訂單編號：${b.id||"—"}`,`入住：${b.startDate||"—"}`,`退房：${b.endDate||"—"}`,`人數：${b.people?`${b.people} 人`:"未填"}`,`姓名：${b.guestName||"未填"}`,`電話：${b.phone||"未填"}`,`Email：${b.email||"未填"}`,`住宿總額：${total>0?`NT$ ${total.toLocaleString("zh-TW")}`:"未設定"}`,`固定訂金：NT$ ${dep.toLocaleString("zh-TW")}`,`目前狀態：待收訂金／待後台確認`,"",`前往營運管理：${url}`].join("\n");const html=`<!doctype html><html><body style="margin:0;padding:0;background:#f4f1e9;font-family:Arial,'Noto Sans TC',sans-serif;color:#173a35"><div style="max-width:620px;margin:0 auto;padding:28px 18px"><div style="background:#173a35;color:#fff;padding:24px;border-radius:16px 16px 0 0"><div style="font-size:12px;letter-spacing:2px;color:#cdbd92">LIJIE'S HOME</div><h1 style="margin:8px 0 0;font-size:24px">${test?"測試新訂單":"收到新訂單"}</h1></div><div style="background:#fff;padding:24px;border-radius:0 0 16px 16px"><p style="margin:0 0 18px;color:#6b756f">${esc(b.startDate||"—")} → ${esc(b.endDate||"—")}・${b.people?`${esc(b.people)} 人`:"人數未填"}</p><table style="width:100%;border-collapse:collapse;font-size:15px"><tr><td style="padding:8px 0;color:#7a8581">訂單編號</td><td style="padding:8px 0;font-weight:700">${esc(b.id||"—")}</td></tr><tr><td style="padding:8px 0;color:#7a8581">客戶</td><td style="padding:8px 0;font-weight:700">${esc(b.guestName||"未填")}</td></tr><tr><td style="padding:8px 0;color:#7a8581">電話</td><td style="padding:8px 0">${esc(b.phone||"未填")}</td></tr><tr><td style="padding:8px 0;color:#7a8581">Email</td><td style="padding:8px 0">${esc(b.email||"未填")}</td></tr><tr><td style="padding:8px 0;color:#7a8581">住宿總額</td><td style="padding:8px 0;font-weight:700">${total>0?`NT$ ${total.toLocaleString("zh-TW")}`:"未設定"}</td></tr><tr><td style="padding:8px 0;color:#7a8581">固定訂金</td><td style="padding:8px 0;font-weight:700">NT$ ${dep.toLocaleString("zh-TW")}</td></tr><tr><td style="padding:8px 0;color:#7a8581">目前狀態</td><td style="padding:8px 0">待收訂金／待後台確認</td></tr></table><div style="margin-top:24px"><a href="${esc(url)}" style="display:inline-block;background:#173a35;color:#fff;text-decoration:none;padding:13px 20px;border-radius:9px;font-weight:700">前往營運管理查看訂單</a></div><p style="margin:18px 0 0;font-size:12px;color:#8b938f">此信僅作新訂單通知，訂單確認、收款、退款與取消請在官網後台操作。</p></div></div></body></html>`;return{subject,text,html,url};}
